コンソールに出る無限ループエラーの修正
Hosi121/todoApp pull request #23
Opened 2024-07-07 13:39 UTC by Shiluco

コンソールに表示されるエラーの修正
エラー内容:useEffect フック内で setState が呼び出され、その結果レンダリングが無限ループに入ってしまう
対策:taskListがすでにソートされていない場合のみ更新する。依存関係をなくす

2024-07-07 14:13 UTC, Hosi121 requested changes

2024-07-07 14:13 UTC, Hosi121 commented on src/component/pages/Home.tsx
>      if (JSON.stringify(taskList) !== JSON.stringify(sortedTasks)) {
ここの上のロジック，三項演算子使ってまとめてください

例：

  useEffect(() => {
    const sortedTasks = taskList.sort((taskA, taskB) => {
      if (taskA.isDone === taskB.isDone) return 0;
      return taskA.isDone ? 1 : -1;
    });

2024-07-07 14:13 UTC, Hosi121 commented on src/component/pages/Home.tsx
task型あるので、any型を使っているところを直してください

2024-07-07 14:13 UTC, Hosi121 commented on src/component/pages/Home.tsx
initialize関数をHomeの外に移して，分離してほしいです
Homeの中で
const [taskList, setTaskList] = useState<Task[]>(initializeTasks);
する感じで

2024-07-08 14:25 UTC, Shiluco commented on src/component/pages/Home.tsx
修正しました

2024-07-08 14:31 UTC, Shiluco commented on src/component/pages/Home.tsx
>      if (JSON.stringify(taskList) !== JSON.stringify(sortedTasks)) {
修正しました。

2024-07-08 14:34 UTC, Shiluco commented on src/component/pages/Home.tsx
taskListの読み込み書き込みを別のファイルに移すということであっていますか？
その場合はアトミックデザインのどのフォルダが適してるでしょうか

2024-07-08 14:38 UTC, Hosi121 commented on src/component/pages/Home.tsx
ロジック的に移さなくてもいいので，同一ファイル内で分離してほしいという話です．

2024-07-09 00:08 UTC, Shiluco commented on src/component/pages/Home.tsx
なるほどです。ちなみにモジュール性上がる気がするので写してもいいですか？
それと自分ごとにはなりますがreactでロジックだけを別ファイルに入れて動かすっていうのを試してみたい。

2024-07-09 01:26 UTC, Hosi121 commented on src/component/pages/Home.tsx
やってみたいならいいけども、ファイルレベルの分離でモジュール性を確保するのは、再利用性を保つ意味合いが強いと思っていて、initializeはここでしか呼ばれないので、今回だと不要なように見えます
やりたいならやってもいいです

2024-07-09 10:05 UTC, Shiluco commented
改めて確認お願い

2024-07-09 10:24 UTC, Hosi121 approved these changes

2024-07-09 10:27 UTC, Hosi121 commented
![image](https://github.com/Hosi121/todoApp/assets/128687243/66cd3d04-f506-4cde-9d84-4497ceb9e979)

2024-07-09 10:28 UTC, merged