Feature/frontend/fetch tasks api
Hosi121/todoApp pull request #26
Opened 2024-08-14 09:50 UTC by Shiluco

react側でapiを投げてタスクの新規作成、編集、消去ができるようになった。

2024-08-15 00:33 UTC, Hosi121 requested changes

2024-08-15 00:33 UTC, Hosi121 commented on frontend/src/component/templates/TaskCard.tsx
> +
APIで抽象化を挟むといいかも
サービスレイヤーを追加して、apiService.tsxみたいなのを作成して、updateTaskのapiの仕組みだけ関数化するとよき
その他のところもそのファイルにまとめれば、まとまりが良くなる（し、毎回アドレスをハードコードする必要もなくなる）

2024-08-15 12:09 UTC, Shiluco commented
- サービスレイヤーとしてservicesていうフォルダーを作る
- api投げる系の非同期関数をApiService.tsxにまとめる
- tasksApiUrlにapiのurlを定義し、使うときはこれから引用する
とりあえずこれをやってpushしたから改めてレビューお願い！

2024-08-15 12:10 UTC, Shiluco commented on frontend/src/component/templates/TaskCard.tsx
> +
リファクタリング完了！
下のコメントに変更内容まとめたよ

2024-08-15 12:27 UTC, Hosi121 requested changes

2024-08-15 12:27 UTC, Hosi121 commented on frontend/src/services/ApiService.tsx
> +const tasksApiUrl = 'http://localhost:8000/tasks';
細かいけど、命名的にはbaseUrlなどが自然かも

2024-08-15 12:27 UTC, Hosi121 commented on frontend/src/services/ApiService.tsx
> +export const initializeTasks = async (): Promise<Task[]> => {
今回は、拡張性を意識しなくてもよいので悩みどころだけど、apiRequest関数などを作るとよりまとまりが出るかも
現状はPUTやDELETEで重複している部分があるので、これを解消するのが目的

GPTに書かせたけど、こんなのが例です（たしかShareTubeでもこういうのがあったはず…）
```
const apiRequest = async (url: string, method: string, body?: object) => {
  const options: RequestInit = {
    method,
    headers: { 'Content-Type': 'application/json' },
  };

  if (body) {
    options.body = JSON.stringify(body);
  }

  const response = await fetch(url, options);

  if (!response.ok) {
    throw new Error('Failed to perform API request');
  }

  return response;
};
```
こうすると
```
export const putTask = async (editedTask: Task) => {
  try {
    await apiRequest(`${tasksApiUrl}/${editedTask.id}`, 'PUT', editedTask);
  } catch (error) {
    console.error('Error:', error);
  }
};
```
こうやって書けるので、見通しが良くなる

2024-08-15 14:10 UTC, Shiluco commented on frontend/src/services/ApiService.tsx
> +export const initializeTasks = async (): Promise<Task[]> => {
ダブってるところがあるからメソッド別に条件分岐させる感じ？

2024-08-15 14:28 UTC, Hosi121 commented on frontend/src/services/ApiService.tsx
> +export const initializeTasks = async (): Promise<Task[]> => {
それぞれのapiの処理の部分をapirequest関数に抽象化してる
なので、メソッド毎に分岐してるとも取れるかも
こうすることで、全体のコードが見やすい＆書きやすいになると思う

2024-08-16 04:27 UTC, Shiluco commented
- urlを定義している変数名をtasksApiUrlをbaseUrlに変更
- apiリクエストの部分を抽象化して他の非同期関数から扱えるように変更
この二つを変更したよ

2024-08-16 05:54 UTC, merged